import 'dart:developer';

import 'package:flutter/material.dart';

class TableColumnConfig {
  final String title;
  final String key;
  final dynamic Function(Map<String, dynamic>)? valueBuilder;

  TableColumnConfig({
    required this.title,
    required this.key,
    this.valueBuilder,
  });
}

final List<TableColumnConfig> dummyColumns = [
  TableColumnConfig(title: 'ID', key: 'id'),
  TableColumnConfig(title: 'Name', key: 'name'),
  TableColumnConfig(title: 'Patient ID', key: 'patientId'),
  TableColumnConfig(title: 'Email', key: 'email'),
  TableColumnConfig(title: 'Phone Number', key: 'phoneNumber'),
  TableColumnConfig(
    title: 'Status',
    key: 'status',
    valueBuilder: (row) {
      return Container(
        padding: const EdgeInsets.all(4),
        color: row['status'] == 'Active' ? Colors.green : Colors.red,
        child: Text(row['status'], style: const TextStyle(color: Colors.white)),
      );
    },
  ),
  TableColumnConfig(
    title: 'Action',
    key: 'action',
    valueBuilder: (row) {
      return Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Edit Button
          ElevatedButton.icon(
            onPressed: () {
              log('Edit row id: ${row['id']}');
              // Add your edit logic here
            },
            icon: const Icon(Icons.edit, size: 16),
            label: const Text('Edit', style: TextStyle(fontSize: 12)),
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 4),
              minimumSize: Size.zero,
            ),
          ),
          const SizedBox(width: 4),
          // Delete Button
          ElevatedButton.icon(
            onPressed: () {
              log('Delete row id: ${row['id']}');
            },
            icon: const Icon(Icons.delete, size: 16),
            label: const Text('Delete', style: TextStyle(fontSize: 12)),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 4),
              minimumSize: Size.zero,
            ),
          ),
        ],
      );
    },
  ),
];

final List<Map<String, dynamic>> dummyRows = [
  {
    'id': 1,
    'name': 'John Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 2,
    'name': 'Sreenu Kareti',
    'patientId': '764542',
    'email': 'sreenu@gmail.com',
    'status': 'Active',
    'phoneNumber': '7095649714',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 3,
    'name': 'osfdiwqfqrw',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 4,
    'name': 'Jdfihfiwfwqe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 5,
    'name': 'jfjfwf Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 6,
    'name': 'LLLLL Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 7,
    'name': 'mmmmmmm',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 8,
    'name': 'aSWIUER Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 9,
    'name': 'John Abraham',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 10,
    'name': 'Nag Aswin',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 1,
    'name': 'John Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 2,
    'name': 'Sreenu Kareti',
    'patientId': '764542',
    'email': 'sreenu@gmail.com',
    'status': 'Active',
    'phoneNumber': '7095649714',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 3,
    'name': 'osfdiwqfqrw',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 4,
    'name': 'Jdfihfiwfwqe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 5,
    'name': 'jfjfwf Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 6,
    'name': 'LLLLL Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 7,
    'name': 'mmmmmmm',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 8,
    'name': 'aSWIUER Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 9,
    'name': 'John Abraham',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 10,
    'name': 'Nag Aswin',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 1,
    'name': 'John Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 2,
    'name': 'Sreenu Kareti',
    'patientId': '764542',
    'email': 'sreenu@gmail.com',
    'status': 'Active',
    'phoneNumber': '7095649714',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 3,
    'name': 'osfdiwqfqrw',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 4,
    'name': 'Jdfihfiwfwqe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 5,
    'name': 'jfjfwf Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 6,
    'name': 'LLLLL Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 7,
    'name': 'mmmmmmm',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 8,
    'name': 'aSWIUER Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 9,
    'name': 'John Abraham',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 10,
    'name': 'Nag Aswin',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 1,
    'name': 'John Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 2,
    'name': 'Sreenu Kareti',
    'patientId': '764542',
    'email': 'sreenu@gmail.com',
    'status': 'Active',
    'phoneNumber': '7095649714',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 3,
    'name': 'osfdiwqfqrw',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 4,
    'name': 'Jdfihfiwfwqe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 5,
    'name': 'jfjfwf Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 6,
    'name': 'LLLLL Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 7,
    'name': 'mmmmmmm',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 8,
    'name': 'aSWIUER Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 9,
    'name': 'John Abraham',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 10,
    'name': 'Nag Aswin',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 1,
    'name': 'John Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 2,
    'name': 'Sreenu Kareti',
    'patientId': '764542',
    'email': 'sreenu@gmail.com',
    'status': 'Active',
    'phoneNumber': '7095649714',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 3,
    'name': 'osfdiwqfqrw',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 4,
    'name': 'Jdfihfiwfwqe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 5,
    'name': 'jfjfwf Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 6,
    'name': 'LLLLL Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 7,
    'name': 'mmmmmmm',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 8,
    'name': 'aSWIUER Doe',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 9,
    'name': 'John Abraham',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
  {
    'id': 10,
    'name': 'Nag Aswin',
    'patientId': '22222',
    'email': 'john@example.com',
    'status': 'Active',
    'phoneNumber': '9875690240',
    'gender': "Male",
    'action': {
      'edit': () => log('Edit id 1'),
      'delete': () => log('Delete id 1'),
    },
  },
];
